# Generated by Django 5.1.2 on 2024-10-25 19:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=21, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=21, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Coordinates',
                'verbose_name_plural': 'Coordinates',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5, verbose_name='Title')),
                ('first', models.CharField(max_length=50, verbose_name='First Name')),
                ('last', models.CharField(max_length=50, verbose_name='Last Name')),
            ],
            options={
                'verbose_name': 'Name',
                'verbose_name_plural': 'Names',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large', models.URLField(max_length=255, verbose_name='Large Image URL')),
                ('medium', models.URLField(max_length=255, verbose_name='Medium Image URL')),
                ('thumbnail', models.URLField(max_length=255, verbose_name='Thumbnail Image URL')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.CharField(max_length=8, verbose_name='Offset')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Timezone',
                'verbose_name_plural': 'Time Zones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=15, verbose_name='Region')),
                ('street', models.CharField(max_length=50, verbose_name='Street')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('postcode', models.IntegerField(verbose_name='Postcode')),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='users.coordinates')),
                ('timezone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='users.timezone')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=50, verbose_name='Type')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('birthday', models.CharField(max_length=50, verbose_name='Birthday')),
                ('registered', models.CharField(max_length=50, verbose_name='Registration Date')),
                ('nationality', models.CharField(default='BR', max_length=2, verbose_name='Nationality')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='users.location')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='users.name')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='users.picture')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('phone', models.JSONField(default=list, verbose_name='Telephone Numbers')),
                ('cell', models.JSONField(default=list, verbose_name='Mobile Numbers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='users.user')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['id'],
            },
        ),
    ]
