version: "3.3"

services:
  django:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: